name: K6 Test Error Replication

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
      - name: Install xk6
        run: go install go.k6.io/xk6/cmd/xk6@latest
      - name: Build custom k6 with extensions
        run: |
          xk6 build --with github.com/grafana/xk6-ts@latest
          xk6 build --with github.com/szkiba/xk6-dotenv@latest
