name: K6 Test Error Replication

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      - name: Install xk6
        run: go install go.k6.io/xk6/cmd/xk6@latest
      - name: Build custom k6 with extensions
        run: |
          xk6 build --with github.com/grafana/xk6-ts@latest --with github.com/szkiba/xk6-dotenv@latest --output ./k6
      - name: Test custom k6 build
        run: |
          ./k6 version
          ./k6 run --help
